export const categoriesContants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAIL: 'GET_ALL_CATEGORIES_FAIL',
}

export const productsContants = {
    GET_PRODUCTS_BY_SLUG_REQUEST: 'GET_PRODUCTS_BY_SLUG_REQUEST',
    GET_PRODUCTS_BY_SLUG_SUCCESS: 'GET_PRODUCTS_BY_SLUG_SUCCESS',
    GET_PRODUCTS_BY_SLUG_FAIL: 'GET_PRODUCTS_BY_SLUG_FAIL',
}